//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Bus_Ticket_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket1
    {
        public int Ticket_No { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string departure { get; set; }
        public string arrival { get; set; }
        public string car_plate { get; set; }
        public string price { get; set; }
    }
}
